on: 
  push:
    branches: 
      - old
name: Publish Website Dry Run
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: PetrovrRuslan/snowdog-yamaha@2.0.0
      env:
        FTP_SERVER: ftp.u0066663.cp.regruhosting.ru
        FTP_USERNAME: actions@u0066663.cp.regruhosting.ru
        FTP_PASSWORD: 7l$,1M+zBXN.
        localDir: "/"
        remoteDir: "/"
