on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: PetrovRuslan/FTP-Deploy-Action@test
      env:
        FTP_SERVER: ftp.u0066663.cp.regruhosting.ru
        FTP_USERNAME: test@u0066663.cp.regruhosting.ru
        FTP_PASSWORD: ${{ secrets.TEST_FTP_PASS }}
        LOCAL_DIR: dist/
        ARGS: 
          --delete
          --exclude=.ftpquota
          --exclude-glob=.git*/** 
          --exclude-glob=.git**
          --exclude=docker-compose.yml
          --exclude=README.md
