name: Deploy-via-ftp-to-test
on: 
  push:
    branches: 
      - old
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upload ftp
      uses: PetrovRuslan/snowdog-yamaha@old
      with:
        host: ftp.u0066663.cp.regruhosting.ru
        user: actions@u0066663.cp.regruhosting.ru
#         password: ${{ secrets.FTP_PASSWORD }}
        password: 7l$,1M+zBXN.
        localDir: "/"
        remoteDir: "/"
