on: push
name: Publish Website
jobs:
  snowdog-yamaha:
    name: snowdog-yamaha
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: PetrovRuslan/snowdog-yamaha@old
      env:
        FTP_SERVER: ftp.u0066663.cp.regruhosting.ru
        FTP_USERNAME: actions@u0066663.cp.regruhosting.ru
        FTP_PASSWORD: 7l$,1M+zBXN.
        # ARGS: --delete
